[package]
name = "poly1305"
version = "0.3.0"
authors = ["RustCrypto Developers"]
license = "MIT OR Apache-2.0"
description = "The Poly1305 universal hash function and message authentication code"
documentation = "https://docs.rs/poly1305"
repository = "https://github.com/RustCrypto/universal-hashes"
keywords = ["crypto", "mac", "umac", "universal-hashing"]
categories = ["cryptography", "no-std"]
readme = "README.md"
edition = "2018"

[dependencies]
universal-hash = { version = "0.2", default-features = false }
zeroize = { version = "0.10", optional = true, default-features = false }

[features]
default = []
std = ["universal-hash/std"]

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "RustCrypto/universal-hashes" }
